export const routes = {
	signUp: "/signup",
	signIn: "/signin",
	forgotPassword: "/forgot-password",
	system: {
		signIn: "/system/signin",
		genericErrorLogs: "/system/error-logs/generic",
		emailErrorLogs: "/system/error-logs/email",
	},
	superAdmin: {
		// companies: "/super-admin/companies",
		// inviteCompanies: "/super-admin/invite-companies",
		// stripeTransactions: "/super-admin/stripe-transactions",
		// stripeConnect: {
		// 	vendors: "/super-admin/stripe-connect/vendors",
		// },
		dashboard: "/admin/dashboard",
		rewards: "/admin/rewards",
		users: "/admin/manage-users",
		settings: "/admin/settings",
	},
	admin: {
		dashboard: "/admin/dashboard",
		products: "/admin/products",
		createProduct: "/admin/products/create",
		productDetails: (id: string) => `/admin/products/${id}`,
		editProduct: (id: string) => `/admin/products/${id}/edit`,
		subscriptions: "/admin/subscriptions",
		teams: "/admin/teams",
		adminDetails: (id: string) => `/admin/dashboard?companyRef=${id}`,
		stripeConnect: {
			main: `/admin/stripe-connect`,
			accountSession: (id: string) => `/admin/stripe-connect/${id}`,
			transferredVendorTransactions: `/admin/stripe-connect/transferred-vendor-transactions`,
			allVendorTransactions: `/admin/stripe-connect/all-vendor-transactions`,
		},
		stripePayment: {
			main: `/admin/stripe-payment`,
			createProduct: `/admin/stripe-payment/create-product`,
			coupons: `/admin/stripe-payment/coupons`,
			createCoupon: `/admin/stripe-payment/coupons/create-coupon`,
			promotionCodes: (id: string) => `/admin/stripe-payment/coupons/${id}/promotion-codes`,
			createPromotionCode: (id: string) => `/admin/stripe-payment/coupons/${id}/promotion-codes/create-promotion-code`,
		},
		rewards: "/admin/rewards",
		users: "/admin/manage-users",
		settings: "/admin/settings",
	},
	user: {
		dashboard: "/user/dashboard",
		products: "/user/products",
		productDetails: (id: string) => `/user/products/${id}`,
		stripeConnect: {
			main: `/user/stripe-connect`,
			productList: `/user/stripe-connect/product-list`,
			pastOrders: `/user/stripe-connect/past-orders`,
			payment: (id: string) => `/user/stripe-connect/product-list/${id}`,
		},
		stripePayment: {
			main: `/user/stripe-payment`,
			productList: `/user/stripe-payment/product-list`,
			checkout: (id: string) => `/user/stripe-payment/product-list/${id}`,
			pastOrders: `/user/stripe-payment/past-orders`,
			paymentStatus: (id: string) => `/user/stripe-payment/payment-status?session_id=${id}`,
		},
	},
	account: {
		profileSettings: "/profile/profile-settings",
		changePassword: "/profile/profile-settings/password",
	},
	profile: {
		dashboard: "/profile",
		shop: "/profile/shop",
	},
};
